module.exports.taskSeed = [
  [
    'Go to ',
    'Plan ',
    'Do the ',
    'Learn ',
    'Listen ',
    'Analize ',
    'Explore ',
    'Research the ',
    'Write about ',
    'Think about ',
    'Make the ',
    'Sell the ',
    'Buy the ',
    'Increase the ',
    'Decrease ',
    'Avoid the ',
    'Come to ',
    'Enter the ',
    'Create ',
    'Print ',
    'Translate ',
    'Read ',
  ],
  [
    'morning exercises ',
    'marketing book ',
    'walk around museum ',
    'travel ',
    'route ',
    'interview ',
    'theater ',
    'cinema ',
    'gym ',
    'bycicle ',
    'transformation ',
    'fast ',
    'exclusive ',
    'books ',
    'bookshelf ',
    'large bed ',
    'paint ',
    'most popular ',
    'most important ',
    'most relevant ',
    'not important ',
    'secondary ',
    'glass ',
    'programs ',
    'instagram ',
    'photos ',
    'military ',
    'perception ',
  ],
  [
    'efficiency ',
    'quality ',
    'finance ',
    'management ',
    'time estimate ',
    'strategy ',
    'to visit ',
    'of the world ',
    'harmony ',
    'borders ',
    'wellness ',
    'kitchen ',
    'body weight ',
    'quantity ',
    'quality ',
    'point ',
    'mockup ',
    'sketch ',
    'variant ',
    'music ',
    'amount ',
    'things ',
    'epic fail ',
    'capability ',
    'benchmark test ',
    'kung-fu things ',
    'for maximum ',
    'just in time ',
    'in my city ',
    'in my life ',
    'of the world ',
  ],
  [
    'and etc ',
    'and think about ',
    'and not forget the ',
    'and give ',
    'and save ',
    'and opportunities ',
    'and similar ',
    'and also ',
    'and the best ',
    'for the ',
    'as the ',
    'or another ',
    'or think baout ',
    'or ',
    'of ',
    'some ',
    'quickly ',
    'optionally ',
    'whenever ',
    'including ',
    'but remember ',
    'but carefully ',
    'but nothing of',
    'without ',
    'catching the ',
    'considering ',
    'summary ',
    'mutch easyer ',
    'about the ',
    'around the ',
    'in the name of ',
  ],
  [
    'money making',
    'apartment',
    'solution',
    'control',
    'destiny',
    'power',
    'way',
    'computer science',
    'of this year',
    'sky',
    'sunday',
    'instance',
    'univercity',
    'universe',
    'it is',
    'best practice',
    'business',
    'miracle',
    'strategy',
    'summer',
    'spring',
    'activity',
    'brainstorm',
    'option',
    'opposition',
    'force',
    'Earth',
    'world',
    'planet',
    'forest',
    'space',
    'experiment',
    'water',
    'time',
  ],
];
